In [1]:
import pandas as pd

In [40]:
df = pd.read_csv('npr.csv')
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [41]:
df['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_df=0.9, min_df=2, stop_words='english')
data = cv.fit_transform(df['Article'])

In [16]:
from sklearn.decomposition import LatentDirichletAllocation
LDA = LatentDirichletAllocation(n_components=7, random_state=42)
LDA.fit(data)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [2]:
len(cv.get_feature_names()), type(cv.get_feature_names())

In [27]:
import random

random_word_id = random.randint(0,54777)

cv.get_feature_names()[random_word_id]

'calculated'

In [29]:
len(LDA.components_), type(LDA.components_)

(7, numpy.ndarray)

In [30]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [31]:
single_topic = LDA.components_[0]

In [32]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [33]:
import numpy as np
arr = np.array([10,200,1])

In [34]:
arr.argsort()

array([2, 0, 1], dtype=int64)

In [35]:
#argsort() ----> INDEX positions sorted from least to greatest
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [38]:
top_20 = single_topic.argsort()[-20:]

for index in top_20:
    print(cv.get_feature_names()[index])

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [39]:
for i, topic in enumerate(LDA.components_):
    print(f"Top WORDS for topics !!! #{i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')

Top WORDS for topics !!! #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


Top WORDS for topics !!! #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


Top WORDS for topics !!! #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


Top WORDS for topics !!! #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


Top WORDS for topics !!! #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']


Top WORDS for topics !!! #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think', 'people', '

In [44]:
topic_results = LDA.transform(data)

In [48]:
topic_results.shape, topic_results[0]

((11992, 7),
 array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
        2.99652737e-01, 2.25479379e-04, 2.25497980e-04]))

In [49]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [53]:
topic_results[0].argmax()

1

In [54]:
df['Topic'] = topic_results.argmax(axis=1) 

In [56]:
df.head(100)

Article  Topic
0   In the Washington of 2016, even when the polic...      1
1     Donald Trump has used Twitter  —   his prefe...      1
2     Donald Trump is unabashedly praising Russian...      1
3   Updated at 2:50 p. m. ET, Russian President Vl...      1
4   From photography, illustration and video, to d...      2
5   I did not want to join yoga class. I hated tho...      3
6   With a   who has publicly supported the debunk...      3
7   I was standing by the airport exit, debating w...      2
8   If movies were trying to be more realistic, pe...      3
9   Eighteen years ago, on New Year’s Eve, David F...      2
10  For years now, some of the best, wildest, most...      5
11  For years now, some of the best, wildest, most...      5
12  The Colorado River is like a giant bank accoun...      2
13  For the last installment of NPR’s holiday reci...      2
14  Being overweight can raise your blood pressure...      3
15  Who’s the YouTube star of 2016? Adele singing ...      5
16  Here’s a quick roundup of some of the   you ma...      2
17  Ben Johnston doesn’t follow the rules of music...      5
18  David Bowie, Prince and George Michael are all...      5
19  In November, the typically straitlaced Office ...      1
20  This is the time of year when everybody is mak...      5
21  Terrorist attacks, hurricanes, a divisive U. S...      6
22  We all experience stress at work, no matter th...      6
23  When John Fahey recorded The New Possibility i...      5
24  This year was one of   hacks, exploding smartp...      6
25  From West Virginia to Wyoming, coal country ov...      4
26  Updated Jan. 1 at 9:56 a. m. ET, At least 39 p...      1
27  On the morning of Jan. 1, Los Angeles resident...      1
28  In September, reproductive endocrinologist Joh...      3
29  In an effort to take advantage of the intimate...      3
..                                                ...    ...
70  After a storm of criticism, including from   D...      4
71  Fox News anchor Megyn Kelly is leaving the cab...      1
72  When spirits entrepreneur Steven Grasse consid...      2
73  Every year in the U. S. more than 30, 000 peop...      3
74     Demarco Webster Jr. was helping his dad mov...      2
75  Ah, to work in France: plenty of vacation and ...      0
76  Viridiana Martinez’s parents brought her to th...      4
77  Beijing’s sky appears blue at the beginning of...      0
78  It’s 1968 in New Bordeaux, La. On the surface ...      5
79  One in five Americans is religiously unaffilia...      4
80  Updated at 1 p. m. ET, Turkish authorities mad...      1
81  When   Miranda was a teenager in the 1990s, he...      5
82  Opening punches were thrown in what one top De...      4
83  Desmond Tutu, South Africa’s former Anglican a...      4
84  If you’re looking for a diet plan that suits y...      3
85  Rex Tillerson,   Donald Trump’s nominee for U....      1
86  Dylann Roof delivered his opening statement in...      1
87  A crowded commuter train crashed into a bumper...      2
88  Amid this week’s firestorm over Republicans’ a...      6
89  Louisiana is losing its coast at a rapid rate ...      2
90  Murmuration refers to the phenomenon that resu...      2
91  Armed men reportedly attacked a jail in the Ph...      1
92  Frenchman Robert Marchand set a new world reco...      2
93  People think of black holes as nightmare vacuu...      6
94  Several civil rights activists were arrested T...      4
95  Vocalist Xenia Rubinos ended 2016 with a bang:...      5
96  Imagine being able to collect the DNA of a hum...      3
97  The machinery inside Conner Bottling Works doe...      2
98  An Israeli military court has convicted a sold...      1
99  ”Dogs are better than human beings,” wrote Emi...      5

[100 rows x 2 columns]